
project_id = "swlqrejfgvmjajhtoall"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[[functions]]
name = "create-payment"
verify_jwt = true

[[functions]]
name = "webhook-payment"
verify_jwt = false

